import { ChangeDetectorRef } from '@angular/core';
import { UniColor } from '../../../core/enums';
import { UniProgressMode } from '../../enums/progress-mode.enum';
import { IUniProgress } from '../../progress.interface';
import * as i0 from "@angular/core";
export declare class UniProgressSpinnerComponent implements IUniProgress {
    private readonly _cdr;
    mode: UniProgressMode;
    color: UniColor;
    get total(): number;
    set total(v: number);
    private _total;
    get value(): number;
    set value(v: number);
    private _value;
    get strokeWidth(): number;
    set strokeWidth(v: number);
    private _strokeWidth;
    get diameter(): number;
    set diameter(v: number);
    private _diameter;
    private readonly _indeterminate;
    get radius(): number;
    get strokeDasharray(): string;
    get strokeDashoffset(): number;
    private get _circumference();
    private get _percentage();
    private get _modeValue();
    private get _modeTotal();
    readonly UniProgressMode: typeof UniProgressMode;
    constructor(_cdr: ChangeDetectorRef);
    static ɵfac: i0.ɵɵFactoryDef<UniProgressSpinnerComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<UniProgressSpinnerComponent, "uni-progress-spinner", ["uniProgressSpinner"], { "mode": "mode"; "color": "color"; "total": "total"; "value": "value"; "strokeWidth": "strokeWidth"; "diameter": "diameter"; }, {}, never>;
}
